[package]
name = "geno"
version = "0.1.0"
authors = ["rsouvik <rsouvik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bio = "0.28.2"
rand = "0.7.3"